### ISSUE TITLE
Remote temperatures reported in F aren't converted to C

### ISSUE THREAD

**Issue by Sammy1Am** [Sammy1Am/mitsubishi-uart#3]
Any sensors providing values in F will not be converted before being sent to the system (likely resulting in an out of range error)

**Comment by KazWolfe** [comment]
Workaround until this is patched in code:

```yml
sensors:
  - platform: homeassistant
    id: living_room_temperature
    entity_id: sensor.airthings_living_room_temperature
    filters:
      - lambda: return ((x - 32.0) * (5.0 / 9.0));
```
