### ISSUE TITLE
Alternate temperature source seems to have no effect

### ISSUE THREAD

**Issue by tjwallace** [Sammy1Am/mitsubishi-uart#7]
I have configured `mitsubishi_uart` to use an alternative temperature source but it doesn't seem to have any effect. The internal temperature source is still used. Any idea how to debug?

```yaml
sensor:
  - id: room_temp
    platform: homeassistant
    entity_id: sensor.snzb_02d_2_temperature
    name: Kitchen Temperature

mitsubishi_uart:
  heatpump_uart: uart_hp
  temperature_sources:
    - room_temp
  supported_fan_modes:
    - AUTO
    - LOW
    - MEDIUM
    - HIGH
  custom_fan_modes: []
  selects:
    vane_position_select:
      id: vane_position_select
      disabled_by_default: true
    horizontal_vane_position_select:
      id: horizontal_vane_position_select
      disabled_by_default: true
```

<img width="326" alt="image" src="https://github.com/Sammy1Am/mitsubishi-uart/assets/91084/2d03858d-1c73-4b34-b5d7-8695f5d27231">
<img width="546" alt="image" src="https://github.com/Sammy1Am/mitsubishi-uart/assets/91084/a8516eba-aca1-48a6-9d64-49de28a9bf76">
